name       : scipy
version    : 1.19.0
release    : 3
source     :
    - https://github.com/scipy/scipy/releases/download/v0.19.0/scipy-0.19.0.tar.xz : ed52232afb2b321a4978e39040d94bf81af90176ba64f58c4499dc305a024437
license    : BSD-3-Clause
component  : programming.python
optimize   : speed
summary    : Scientific Library for Python
description: |
    SciPy is open-source software for mathematics, science, and engineering.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - cython
    - numpy
    - openblas-devel
    - python-setuptools
rundeps    :
    - numpy
    - python-pillow
build      : |
    export LDFLAGS="-Wall -shared"
    %python_setup --fcompiler=gnu95
    %python3_setup --fcompiler=gnu95
install    : |
    export LDFLAGS="-Wall -shared"
    %python_install
    %python3_install
