name       : scipy
version    : 1.8.0
release    : 26
source     :
    - https://files.pythonhosted.org/packages/source/s/scipy/scipy-1.8.0.tar.gz : 31d4f2d6b724bc9a98e527b5849b8a7e589bf1ea630c33aa563eda912c9ff0bd
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
    - Qhull
component  : programming.python
optimize   : speed
summary    : Scientific Library for Python
description: |
    SciPy is open-source software for mathematics, science, and engineering.
avx2       : yes
builddeps  :
    - pkgconfig(python3)
    - cython
    - numpy
    - pybind11
    - openblas-devel
    - python-pythran
rundeps    :
    - numpy
    - python-pillow
setup      : |
    %patch -p1 < $pkgfiles/0001-Call-the-right-cython-executable.patch
build      : |
    export LDFLAGS="-Wall -shared"
    %python3_setup
install    : |
    export LDFLAGS="-Wall -shared"
    %python3_install
    if [[ ! -z "${AVX2BUILD}" ]]; then
        %python3_avx2_lib_shift
    fi
