name       : scipy
version    : 0.18.0
release    : 1
source     :
    - https://pypi.python.org/packages/01/a1/dce70d47377d662aa4b0895df8431aee92cea6faefaab9dae21b0f901ded/scipy-0.18.0.tar.gz : f01784fb1c2bc246d4211f2482ecf4369db5abaecb9d5afb9d94f6c59663286a
license    : BSD-3-Clause
summary    : Scientific Library for Python
description: |
    SciPy is open-source software for mathematics, science, and engineering.
builddeps  :
    - pkgconfig(lapack)
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - cython
    - numpy
    - openblas-devel
    - python-setuptools
rundeps    :
    - numpy
    - python-pillow
build      : |
    export LDFLAGS="-Wall -shared"
    %python_setup
    %python3_setup
install    : |
    export LDFLAGS="-Wall -shared"
    %python_install
    %python3_install