name       : scipy
version    : 1.9.0
release    : 29
source     :
    - https://github.com/scipy/scipy/releases/download/v1.9.0/scipy-1.9.0.tar.gz : c0dfd7d2429452e7e94904c6a3af63cbaa3cf51b348bd9d35b42db7e9ad42791
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
    - Qhull
component  : programming.python
summary    : Scientific Library for Python
description: |
    SciPy is open-source software for mathematics, science, and engineering.
networking : yes
optimize   :
    - speed
builddeps  :
    - pkgconfig(lapack)
    - pkgconfig(python3)
    - pkgconfig(openblas)
    - cython
    - numpy
    - patchelf
    - pybind11
    - python-pythran
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
rundeps    :
    - numpy
    - python-pillow
setup      : |
    # Borrowed from Arch
    sed -e 's|lapack=openblas|lapack=lapack|' -i meson.build
    sed -e 's|==|>=|g' -e 's|\,<[0-9]*\(.[0-9]\)*||g' -i pyproject.toml
build      : |
    # We don't have meson-python packaged yet
    export PYTHONUSERBASE=$workdir
    export PATH=$PATH:$workdir/bin/
    pip3 install --user meson-python

    # We can't explicity use PEP517 with current macros if a setup.py file exists
    python3 -m build --wheel --no-isolation
install    : |
    python3 -m installer --destdir="$installdir" dist/*.whl
