name       : scipy
version    : 0.19.1
release    : 9
source     :
    - https://github.com/scipy/scipy/archive/v0.19.1.tar.gz : ac268fe92edd149c6f52fa138d2a03877c080981d7944e96bab8ef68764f71cc
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
    - Qhull
component  : programming.python
optimize   : speed
summary    : Scientific Library for Python
description: |
    SciPy is open-source software for mathematics, science, and engineering.
builddeps  :
    - cython
    - numpy
    - openblas-devel
    - python-setuptools
rundeps    :
    - numpy
    - python-pillow
build      : |
    export LDFLAGS="-Wall -shared"
    %python_setup --fcompiler=gnu95
    %python3_setup --fcompiler=gnu95
install    : |
    export LDFLAGS="-Wall -shared"
    %python_install
    %python3_install
