name       : scipy
version    : 1.6.0
release    : 19
source     :
    - https://github.com/scipy/scipy/archive/v1.6.0.tar.gz : 51bd3c4799c545b8f11232a09cd824f99a0ea4daa6df612312ff40be11451ea8
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
    - Qhull
component  : programming.python
optimize   : speed
summary    : Scientific Library for Python
description: |
    SciPy is open-source software for mathematics, science, and engineering.
builddeps  :
    - pkgconfig(python3)
    - cython
    - numpy
    - pybind11
    - openblas-devel
rundeps    :
    - numpy
    - python-pillow
build      : |
    export LDFLAGS="-Wall -shared"
    %python3_setup --fcompiler=gnu95
install    : |
    export LDFLAGS="-Wall -shared"
    %python3_install
