name       : scipy
version    : 1.6.3
release    : 22
source     :
    - https://github.com/scipy/scipy/releases/download/v1.6.3/scipy-1.6.3.tar.xz : 3851fdcb1e6877241c3377aa971c85af0d44f90c57f4dd4e54e1b2bbd742635e
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
    - Qhull
component  : programming.python
optimize   : speed
summary    : Scientific Library for Python
description: |
    SciPy is open-source software for mathematics, science, and engineering.
avx2       : yes
builddeps  :
    - pkgconfig(python3)
    - cython
    - numpy
    - pybind11
    - openblas-devel
rundeps    :
    - numpy
    - python-pillow
build      : |
    export LDFLAGS="-Wall -shared"
    %python3_setup --fcompiler=gnu95
install    : |
    export LDFLAGS="-Wall -shared"
    %python3_install
    if [[ ! -z "${AVX2BUILD}" ]]; then
        %python3_avx2_lib_shift
    fi
