name       : scipy
version    : 1.0.0
release    : 13
source     :
    - https://github.com/scipy/scipy/archive/v1.0.0.tar.gz : c423a4511684554958dab55f2877df78e765b44f8eef46d5425891d6ac3b49bc
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
    - Qhull
component  : programming.python
optimize   : speed
summary    : Scientific Library for Python
description: |
    SciPy is open-source software for mathematics, science, and engineering.
builddeps  :
    - cython
    - numpy
    - openblas-devel
    - python-setuptools
rundeps    :
    - numpy
    - python-pillow
build      : |
    export LDFLAGS="-Wall -shared"
    %python_setup --fcompiler=gnu95
    %python3_setup --fcompiler=gnu95
install    : |
    export LDFLAGS="-Wall -shared"
    %python_install
    %python3_install
