name       : scipy
version    : 1.1.0
release    : 16
source     :
    - https://github.com/scipy/scipy/archive/v1.1.0.tar.gz : 0291a2254d9a020af9b49ca648e8b41e1366be9a8a40849be9102626b2022422
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
    - Qhull
component  : programming.python
optimize   : speed
summary    : Scientific Library for Python
description: |
    SciPy is open-source software for mathematics, science, and engineering.
builddeps  :
    - cython
    - numpy
    - openblas-devel
    - python-setuptools
rundeps    :
    - numpy
    - python-pillow
build      : |
    export LDFLAGS="-Wall -shared"
    %python_setup --fcompiler=gnu95
    %python3_setup --fcompiler=gnu95
install    : |
    export LDFLAGS="-Wall -shared"
    %python_install
    %python3_install
