name       : scipy
version    : 0.18.1
release    : 2
source     :
    - https://pypi.python.org/packages/22/41/b1538a75309ae4913cdbbdc8d1cc54cae6d37981d2759532c1aa37a41121/scipy-0.18.1.tar.gz : 8ab6e9c808bf2fb3e8576cd8cf07226d9cdc18b012c06d9708429a821ac6634e
license    : BSD-3-Clause
component  : programming.python
optimize   : speed
summary    : Scientific Library for Python
description: |
    SciPy is open-source software for mathematics, science, and engineering.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - cython
    - numpy
    - openblas-devel
    - python-setuptools
rundeps    :
    - numpy
    - python-pillow
build      : |
    export LDFLAGS="-Wall -shared"
    %python_setup --fcompiler=gnu95
    %python3_setup --fcompiler=gnu95
install    : |
    export LDFLAGS="-Wall -shared"
    %python_install
    %python3_install
